force-app/main/default/objects/API_Request_History__c/API_Request_History__c.object-meta.xml
<CustomObject>
    <label>API Request History</label>
    <nameField>
        <displayFormat>ARH-{00000}</displayFormat>
        <label>API Request History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Request Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Request_History__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_Request_History__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/API_Request_History__c/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <label>Headers</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_Request_History__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Request_History__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RequestHistoryService.cls
public with sharing class RequestHistoryService {
    @AuraEnabled
    public static void saveRequestHistory(String method, String endpoint, String headers, String body, String response ) {
        API_Request_History__c history = new API_Request_History__c();
        history.Method__c = method;
        history.Endpoint__c = endpoint;
        history.Headers__c = headers;
        history.Body__c = body;
        history.Response__c = response;
        insert history;
    }

    @AuraEnabled
    public static List<API_Request_History__c> getRequestHistory() {
        return [SELECT Id, Method__c, Endpoint__c FROM API_Request_History__c ORDER BY CreatedDate DESC LIMIT 10];
    }
}